### ISSUE TITLE
Logging levels are WRONG for data platform apps

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/smart_city#15]
"As a system administrator,
I want to know what events have occurred in the system, and who initiated them,
So that I can investigate problems and security concerns.

Acceptance criteria:
* This can probably be drilled down on in grooming in terms of what level of detail goes with what level of logging (emit each record == debug?)
** Logging should be parameterizable per environment. Ideally, we should on be getting warn or error level logs in Kibana for prod.

Tech notes:
* For elixir based apps, log levels should be configurable per environment, either through app configuration or parsing out and filtering on the log level in fluentd or kibana.
* For non-elixir based apps (Kafka, Zookeeper, Presto, etc.) parsing is a bit more varied and complex,  and it may be best just to parameterize the app log levels per environment.

06-24-19: Migrated from SMRT-1175"

**Comment by rob-h-m** [comment]
Moved to SCD
