### ISSUE TITLE
Project Evaluators and any LDAP users can log into VPN

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/smart_city#16]
"Currently anyone who has an LDAP account can log into the vpn giving them access to various resources which are supposed to be private.  This should be controlled by something like group membership which keeps people such as project evaluators from logging into VPN (and as such jenkins, grafana, etc)

 

06-24-19: Migrated from SMRT-1273"

**Comment by rob-h-m** [comment]
Moved to SCOS
