### ISSUE TITLE
Ingest outstanding datasets

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/smart_city#17]
"As a data consumer

I would like to have the remaining datasets available locally

So that I can still access the datasets I already know and love.

AC: 
 * Ingest these datasets, once performance improvements are complete and this can be done
 * Change them from remote to local.  They were temporarily made remote with SMRT-1365

Dataset IDs:
 # {{12938d01-ace3-4945-9295-1ff7a6672a53}}
 # {{b7f74914-b6ed-43d6-8831-bb4e1a555d7b}}
 # {{7ab08634-3eda-4b05-a754-5eb6cab31326}}
 # {{03e2736e-c3ec-4677-91d7-a73a8dc0b7fb}}
 # {{6979a564-6f6c-4178-85e8-1fc9c9776bce}}
 # {{2ffa6cac-b2e3-4459-a77d-f5ec70b978cc}}
 # {{d5678a98-c1af-4fa9-8fd8-b8d853cec83e}}
 # {{9f505fb2-e6a3-46f9-b004-930b28a284fb}}
 # {{e6a79269-cdf8-4909-8fe1-e4c99e3bb658}}
 # {{f2c5b958-a88e-4700-bfbe-2c116ad05cb5}}

 

06-24-19: Migrated from SMRT-1366"

**Comment by rob-h-m** [comment]
Moved to SCOS
