### ISSUE TITLE
MAPCD API Uploads

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/smart_city#20]
"As a program evaluator,
I want to see data from the MAPCD project in the OS,
So that I can verify the goals of the program are being met.

Acceptance Criteria:
 * Ingest data from MAPCD via the API

Tech Notes:
 * The API was tested in February as part of SMRT-927

06-24-19: Migrated from SMRT-1215"

**Comment by rob-h-m** [comment]
Moved to SCOS
