### ISSUE TITLE
Verify SFTP Data Ingestion - CareSource

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/smart_city#22]
"As a Medical Care Organization (CareSource), 
I want to ingest my Prenatal Trip Assistance project and control data into the OS, 
so that the project can be evaluated.

Acceptance Criteria:
 * Test the code written in SMRT-1037 with external data once the providers have it ready for us

06-24-19: Migrated from SMRT-1318"

**Comment by rob-h-m** [comment]
Moved to SCOS
