### ISSUE TITLE
Ingest Program Level KPIs

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/smart_city#23]
"AC:

Ingest below datasets
 * Ohio Fuel Prices
 * MORPC Traffic Counts (AADT)
 * MORPC Turning Movement Counts (TMC)
 * ODOT AADT
 * ODOT Construction Activities
 ** Current
 ** Last 4 years
 ** Next 4 years
 * Weather Data
 * Traffic Incidents (ODOT-GCAT Crashes/Incidents)

Notes:
 * Created S3 bucket in scos-alm under the name [scos-alm-ckan-csv-backup|https://s3.console.aws.amazon.com/s3/buckets/scos-alm-ckan-csv-backup/?region=us-east-2&tab=overview]  > [public] > [Program Level KPI]
 * Created one folder for each dataset and its data dictionary
  

06-24-19: Migrated from SMRT-1397"

**Comment by rob-h-m** [comment]
Moved to SCOS
