### ISSUE TITLE
Ingest INRIX Data (Program Level KPI)

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/smart_city#24]
"AC:
 * Ingest INRIX data

Notes from Ram:
 * INRIX data is approximately close to 40 GB. This data is currently available in 6 parts (6 csv files). Ram will have to combine these CSV files into one.
 * 
Since the dataset is the same as previous, data dictionary will also be the same.
[|https://jira.smartcolumbusos.com/secure/AddComment!default.jspa?id=13724]

06-24-19: Migrated from SMRT-1398"

**Comment by rob-h-m** [comment]
Moved to SCOS
