### ISSUE TITLE
Migrate May and September COTA Ridership data from CKAN to 2.0

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/smart_city#25]
"AC:
 * Migrate COTA ridership data for
 ** May trimester (3 csv files)
 ** September trimester (3 csv files)

[https://ckan.smartcolumbusos.com/dataset/cota-unlinked-passenger-trips-data-05-2017-04-2018]

 

06-24-19: Migrated from SMRT-1406"

**Comment by rob-h-m** [comment]
Moved to SCOS
