### ISSUE TITLE
Spike: automating patch management for most things

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/smart_city#26]
"AS Andy the SCOS System Administrator,
 I WANT to keep all components of the Operating System up to date,
 SO THAT any security vulnerabilities that arise are patched before they expose the system to risk.

Acceptance Criteria:
 * The following applications need to have analysis on their ability to have automatically applied patch management, have a strategy designed, and a card created to implement that strategy.
 ** Joomla
 ** OpenVPN
 ** FreeIPA
 ** EC2
 ** EKS
 ** Jenkins
 ** ECS workers
 ** RDS
 ** Elastic Cache
 ** Kafka/Strimzi
 ** Logging Stack
 ** Monitoring Stack
 ** Presto stack (hive, minio)
 ** Lime Survey
 * Document the decision for each of these choices in scosopedia. 
 ** If it makes proper business sense, these can individually be opted out of automatic update procedures, we just have to make that decision.

Note, this came from the pre-groomed list of cards, from meetings with Warner, Johnson, Jessie, Ben B and Rob.

06-24-19: Migrated from SMRT-1331"

**Comment by rob-h-m** [comment]
Moved to SCOS
