### ISSUE TITLE
System updates on EC2 instances - LDAP

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/smart_city#27]
"AS Andy the SCOS System Administrator,
 I WANT to keep all components of the Operating System up to date,
 SO THAT any security vulnerabilities that arise are patched before they expose the system to risk.

Acceptance Criteria:
 * The host operating system is the most current LTS version
 * All installed packages on the operating system are updated to their most recent version
 * FreeIPA is the most current version

Note, this came from the pre-groomed list of cards, from meetings with Warner, Johnson, Jessie, Ben B and Rob.

06-24-19: Migrated from SMRT-1336"

**Comment by rob-h-m** [comment]
Moved to SCOS
