### ISSUE TITLE
Review Presto database (RDS) to ensure that updates are administrated

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/smart_city#28]
"AS Andy the SCOS System Administrator,
 I WANT to keep all components of the Operating System up to date,
 SO THAT any security vulnerabilities that arise are patched before they expose the system to risk.

Acceptance Criteria:
 * Enable semi-automatic service version updating
 * Enable backups
 * A method exists which allow new managed services to automatically be provisioned with these policies.
 * Existing backups are within the new retention and encryption policies
 * Identify a way to be notified of available updates to these services.
 * Write cards with what is learned to perform the same actions for Joomla and Lime Survey's RDS databases.

Technical Notes:
 - Many of these may be implemented or half implemented.
 - Pick a reasonable (2 weeks), time to keep backups and a reasonable cadence to take backups (every 24 hours) 

Note, this came from the pre-groomed list of cards, from meetings with Warner, Johnson, Jessie, Ben B and Rob.

06-24-19: Migrated from SMRT-1339"

**Comment by rob-h-m** [comment]
Moved to SCOS
